### ISSUE TITLE
C# SDK

### ISSUE THREAD

**Issue by jchannon** [publichealthengland/coronavirus-dashboard-api-python-sdk#5]
Hi, 

Apologies that this is not python related but I've written a C# SDK if you are interested in taking ownership of it? It has most of the functionality and a sample app to demonstrate it's use. I saw you had R, Python & Javascript and wondered if you'd want a C# one too?

Here's the repo if you'd like it - https://github.com/jchannon/coronavirus-dashboard-api-net-sdk

Thanks!

**Comment by xenatisch** [comment]
@jchannon Thank you for the offer, we are very grateful. We will be more than happy to take ownership and maintain the service. 

Would you rather transfer the ownership to PHE via GitHub, or shall I create fork and redeploy the code to our repository? I would like to ensure that your contribution is recorded in the history of the project, and I will ensure that you are adequately acknowledged in any documentation.

**Comment by jchannon** [comment]
I’ll transfer it via Github. Glad my contribution might help someone!

**Comment by jchannon** [comment]
You might have to make me a member of your org whilst I transfer
https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#repository-transfers-and-organizations

**Comment by xenatisch** [comment]
@jchannon I'm afraid I can't make you a member of the organisation because of the private repositories that we have. It needs authorisation from a whole lot of people - I'm sure you can imagine. 

You could transfer it to me, and I will then transfer it to PHE. That's probably the easiest way to do it.

**Comment by jchannon** [comment]
I completely understand!

I've sent a transfer request to you ready for you to transfer to PHE!

**Comment by xenatisch** [comment]
@jchannon it's all done: https://github.com/publichealthengland/coronavirus-dashboard-api-net-sdk

It's absolutely amazing... you have even followed my design pattern which I have used across all SDKs. 

Once again, thank you for your contribution.

**Comment by jchannon** [comment]
No problem at all. I’m really glad I could do this. Brings some meaning to
sitting a desk all day.

If you’d like to raise any issues then I’ll happily fix them for you. I can
start by setting up a CI pipeline if you like and work on releasing a
package to Nuget which is .Net version of npm. Just let me know what you
think is most of priority.

Thanks again

**Comment by xenatisch** [comment]
So the way I have been doing it for Python and JS is that I created a GitHub Actions script which runs a bunch of UnitTests and if successful, deploys the package onto its respective package manager (PyPI or NPM). 

Of course releasing packages on CRAN for R is a whole different story... one which I have been writing since Friday last week, and it's still going on. 

I think releasing the library on Nuget is a great idea. I haven't used C# in years - although I did write the API Manager's policies for the Coronavirus API in C#, mainly because I didn't have a choice! So any help on packing, writing the CI, etc is greatly appreciated... not that you haven't done enough so far. 

I'll start working on the README file in the meantime.

**Comment by jchannon** [comment]
Cool!

I’ll make a fork and setup GH Actions. You’ll need to create a nuget
account for PHE I’d imagine.

I’ve worked in .Net since 2003 so unfortunately know all the traps! However
I’ve recently started working in F# to escape the C# madness!

**Comment by xenatisch** [comment]
F# reminds me Haskell for some reason... I used to work with VB6 back in 98-99, then VB.net, then C#, then just gave up on them all. 

Anyhow, I have already created a PHE organisational account on Nuget. The API key is in GitHub secrets under `NUGET_PUBLISH_KEY`.

**Comment by jchannon** [comment]
Yup it is Haskell-ish :)

Don’t blame you giving it up , ha ha

Thanks for setting up nuget

**Comment by xenatisch** [comment]
Thanks Johnathan. Really appreciate your help.
